import type { Metadata } from 'next'
import { Noto_Serif_KR } from 'next/font/google'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type Props = Readonly<{
  children: React.ReactNode
}>

const notoSans = Noto_Serif_KR({
  weight: ['400', '500', '900'],
  preload: false,
})

export default function RootLayout({ children }: Props) {
  return (
    <html lang="ko">
      <body className={`${notoSans.className} antialiased`}>{children}</body>
    </html>
  )
}
